const fs = require('fs');
let code = fs.readFileSync('src/components/admin/AdminSettings.tsx', 'utf-8');

// Undo the mess
code = code.replace(/{activeTab === 'contact' && \(\n        <div className="space-y-8">\n        {activeTab === 'contact' && \(\n        <div className="space-y-8">\n        {\/\* Kontaktuppgifter \*\/}/g, '{/* Kontaktuppgifter */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'hero' && \(\n        <div className="space-y-8">\n        {activeTab === 'hero' && \(\n        <div className="space-y-8">\n        {\/\* Startsida Hero text & bild \*\/}/g, '        {/* Startsida Hero text & bild */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'about' && \(\n        <div className="space-y-8">\n        {activeTab === 'about' && \(\n        <div className="space-y-8">\n        {\/\* Om mig \/ Om hantverket \*\/}/g, '        {/* Om mig / Om hantverket */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'info' && \(\n        <div className="space-y-8">\n        {activeTab === 'info' && \(\n        <div className="space-y-8">\n        {\/\* Frakt & leverans \(Innehåll\) \*\/}/g, '        {/* Frakt & leverans (Innehåll) */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'search' && \(\n        <div className="space-y-8">\n        {activeTab === 'search' && \(\n        <div className="space-y-8">\n        {\/\* Populära söktermer \(Sökmodal\) \*\/}/g, '        {/* Populära söktermer (Sökmodal) */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'footer' && \(\n        <div className="space-y-8">\n        {activeTab === 'footer' && \(\n        <div className="space-y-8">\n        {\/\* FOOTER SECTION \*\/}/g, '        {/* FOOTER SECTION */}');
code = code.replace(/        <\/div>\n        \)}\n\n        {activeTab === 'orders' && \(\n        <div className="space-y-8">\n          <div className="bg-\[#FBF9F5\] border border-\[#E6DFD3\] rounded-3xl p-6 sm:p-8 text-center space-y-3\">\n            <ShoppingBag className="w-8 h-8 text-\[#6B8E7B\] mx-auto opacity-50\" \/>\n            <h2 className="font-serif text-xl text-\[#242D27\] font-medium\">\n              Beställningar & meddelanden\n            <\/h2>\n            <p className="text-xs text-\[#66726A\]\">\n              Inga redigerbara inställningar för närvarande.\n            <\/p>\n          <\/div>\n        <\/div>\n        \)}\n\n        {activeTab === 'orders' && \(\n        <div className="space-y-8">\n          <div className="bg-\[#FBF9F5\] border border-\[#E6DFD3\] rounded-3xl p-6 sm:p-8 text-center space-y-3\">\n            <ShoppingBag className="w-8 h-8 text-\[#6B8E7B\] mx-auto opacity-50\" \/>\n            <h2 className="font-serif text-xl text-\[#242D27\] font-medium\">\n              Beställningar & meddelanden\n            <\/h2>\n            <p className="text-xs text-\[#66726A\]\">\n              Inga redigerbara inställningar för närvarande.\n            <\/p>\n          <\/div>\n        <\/div>\n        \)}\n\n        {\/\* Submit \*\/}/g, '        {/* Submit */}');

fs.writeFileSync('src/components/admin/AdminSettings.tsx', code);
console.log("Restored");
